// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctxxhmelarekvxmmbdda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0eHhobWVsYXJla3Z4bW1iZGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDIxMTgsImV4cCI6MjA2NTUxODExOH0.yHMlFOBXyOzRmu9_0Kxhksd4EZd8Kn00MniKMwTIxmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);